version: '3'
services:
  warehouse:
    build: warehouse/.
    ports:
      - "3001:3001"
    hostname: warehouse
  order:
    build: order/.
    ports:
      - "3002:3002"
    hostname: order
  payment:
    build: payment/.
    ports:
      - "3003:3003"
    hostname: payment
  apigateway:
    build: apiGateway/.
    ports:
      - "3000:3000"
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    hostname: rabbitmq
